---
- name: Update Package Cache
  yum:
    update_cache: yes

- name: Install Opsview dependencies
  become: yes
  become_user: exadmn
  yum:
    name:
      - epel-release
      - wget
      - rpcbind
      - perl
      - bind-utils
      - ksh
      - vnstat
    state: present

- name: Check If Opsview already downloaded or not
  become: yes
  become_user: root
  stat:
    path: /root/opsview-agent-6.8.0.202212070943-1.el8.x86_64.rpm
  register: file_exist

- name: Download the package if it is not exist
  become: yes
  become_user: root
  get_url:
    url: https://opsview-repository.s3-eu-west-1.amazonaws.com/opsview-agents/centos8/opsview-agent-6.8.0.202212070943-1.el8.x86_64.rpm
    dest: /root/opsview-agent-6.8.0.202212070943-1.el8.x86_64.rpm
  when: not file_exist.stat.exists

- name: Ensure the Opsview-user is created
  become: yes
  become_user: root
  user:
    name: opsview
    state: present

- name: Install Opsview RPM package
  become: yes
  become_user: root
  command: rpm -i /root/opsview-agent-6.8.0.202212070943-1.el8.x86_64.rpm
  args:
    creates: /opt/opsview/agent

- name: Start Opsview Agent
  become: yes
  become_user: root
  service:
    name: opsview-agent
    state: started
    enabled: yes

- name: Get the status of the firewalld service
  service_facts:

- name: Show the status of firewalld service
  debug:
    var: ansible_facts.services['firewalld.service']['status']

- name: Ensure firewalld service is running
  become: yes
  become_user: root
  service:
    name: firewalld
    state: started
    enabled: yes
  when: ansible_facts.services['firewalld.service']['status'] != 'masked'

- name: Allow Opsview IP through firewalld
  become: yes
  become_user: root
  ansible.posix.firewalld:
    rich_rule: 'rule family="ipv4" source address="94.75.230.111/32" accept'
    state: enabled
    permanent: yes
  when: ansible_facts.services['firewalld.service']['status'] != 'masked'

- name: Allow Bareos IP & PORTS through firewalld
  become: yes
  become_user: root
  ansible.posix.firewalld:
    rich_rule: 'rule family="ipv4" source address="212.83.154.138/32" port port="9101-9103" protocol="tcp" accept'
    state: enabled
    permanent: yes
  when: ansible_facts.services['firewalld.service']['status'] != 'masked'

- name: Reload firewalld-service to apply the changes
  become: yes
  become_user: root
  command: firewall-cmd --reload
  async: 0
  poll: 0
  when: ansible_facts.services['firewalld.service']['status'] != 'masked'

- name: Add Opsview Ip address in csf.allow file
  become: yes
  become_user: root
  command: csf -a 94.75.230.111 opsview-server
  when: ansible_facts.services['firewalld.service']['status'] == 'masked'

- name: Add Bareos Ip address in csf.allow file
  become: yes
  become_user: root
  command: csf -a 212.83.154.138 bareos-backup-service
  when: ansible_facts.services['firewalld.service']['status'] == 'masked'

- name: Add allowed ports in csf.conf file
  become: yes
  become_user: root
  lineinfile:
    path: /etc/csf/csf.conf
    regexp: "^TCP_IN = "
    line: 'TCP_IN = "20,21,22,25,26,53,80,110,143,443,465,587,993,3260,995,2077,2078,2079,2080,2082,2083,2086,2087,2095,2096,8443,2662,31262,5666,54741,52460,9101,9102,9103,49152:65534"'
    create: yes
  when: ansible_facts.services['firewalld.service']['status'] == 'masked'

- name: Restart CSF
  become: yes
  become_user: root
  command: csf -r
  when: ansible_facts.services['firewalld.service']['status'] == 'masked'

- name: Add special permissions to sudoers file
  become: yes
  become_user: root
  blockinfile:
    path: /etc/sudoers
    insertafter: "^## Allows members of the users group to shutdown this system"
    block: |
      opsview ALL=NOPASSWD:/usr/sbin/csf
      opsview ALL=NOPASSWD:/usr/sbin/exim
      opsview ALL=NOPASSWD:/usr/sbin/lfd
      opsview ALL=NOPASSWD:/usr/bin/omreport
      opsview ALL=NOPASSWD:/opt/opsview/agent/plugins/check_tcp
      opsview ALL=NOPASSWD:/opt/opsview/agent/plugins/check_disk
    create: yes

- name: Copy the NRPE configuration file
  become: yes
  become_user: root
  copy:
    src: ../../../nrpe.cfg
    dest: /opt/opsview/agent/etc/nrpe.cfg

- name: Copy the check_bandwidth_quota file
  become: yes
  become_user: root
  copy:
    src: ../../../plugins/check_bandwidth_quota.sh
    dest: /opt/opsview/agent/plugins
    group: opsview
    mode: "0750"

- name: Copy the check_csf file
  become: yes
  become_user: root
  copy:
    src: ../../../plugins/check_csf
    dest: /opt/opsview/agent/plugins
    group: opsview
    mode: "0750"

- name: Copy the check_eximmailqueue file
  become: yes
  become_user: root
  copy:
    src: ../../../plugins/check_eximmailqueue
    dest: /opt/opsview/agent/plugins
    group: opsview
    mode: "0750"

- name: Ensure the vnstat service is restarted
  become: yes
  become_user: root
  systemd:
    name: vnstat
    state: restarted

- name: Ensure the opsview service is restarted
  become: yes
  become_user: root
  systemd:
    name: opsview-agent
    state: restarted
