---
- name: Auto-Deploy Opsview Agent
  hosts: all
  become: true
  become_user: exadmn

  tasks:
    - name: Identify Opsview Agent role for Windows
      include_role:
        name: "opsview_windows"
      when: ansible_system == 'Windows'

    - name: Identify Opsview Agent role for Linux
      include_role:
        name: "opsview_{{ ansible_facts['distribution'] | lower }}"
        become: true
        become_user: exadmn
      when: ansible_system != 'Windows'
