---
- name: Check if cpanel service is installed
  command: "systemctl is-active cpanel"
  ignore_errors: true
  register: cpanel_status

- name: Check if 'CSF' service is installed
  command: "systemctl is-active csf"
  ignore_errors: true
  register: csf_status

- name: Download CSF archive
  get_url:
    url: "https://download.configserver.com/csf.tgz"
    dest: "/tmp/csf.tgz"
  when: cpanel_status.rc == 0 and csf_status.rc != 0

- name: Untar CSF archive
  ansible.builtin.unarchive:
    src: "/tmp/csf.tgz"
    dest: "/tmp/"
    remote_src: yes
  when: cpanel_status.rc == 0 and csf_status.rc != 0

- name: Change to CSF directory and install CSF
  become: yes
  become_user: root
  command:
    cmd: "bash install.sh"
    chdir: "/tmp/csf"
  when: cpanel_status.rc == 0 and csf_status.rc != 0

- name: Install Opsview dependencies
  become: yes
  become_user: root
  apt:
    name:
      - wget
      - vnstat
    state: present

- name: Check If Opsview already downloaded or not
  become: yes
  become_user: root
  stat:
    path: /root/opsview-agent_6.8.0.202212070943-1focal1_amd64.deb
  register: file_exist

- name: Download the package if it is not exist
  become: yes
  become_user: root
  get_url:
    url: https://opsview-repository.s3-eu-west-1.amazonaws.com/opsview-agents/ubuntu20/opsview-agent_6.8.0.202212070943-1focal1_amd64.deb
    dest: /root/opsview-agent_6.8.0.202212070943-1focal1_amd64.deb
  when: not file_exist.stat.exists

- name: Install Opsview DEB package
  become: yes
  become_user: root
  command: dpkg -i /root/opsview-agent_6.8.0.202212070943-1focal1_amd64.deb
  args:
    creates: /opt/opsview/agent

- name: Start Opsview Agent
  become: yes
  become_user: root
  service:
    name: opsview-agent
    state: started
    enabled: yes

- name: Add Opsview Ip address in csf.allow file
  become: yes
  become_user: root
  command: csf -a 94.75.230.111 opsview-server

- name: Add Bareos Ip address in csf.allow file
  become: yes
  become_user: root
  command: csf -a 212.83.154.138 bareos-backup-service

- name: Change 'lfd will not start while this is enabled' in csf.conf file
  become: yes
  become_user: root
  lineinfile:
    path: /etc/csf/csf.conf
    regexp: '^TESTING = "1"'
    line: 'TESTING = "0"'
    create: yes

- name: Add allowed ports in csf.conf file
  become: yes
  become_user: root
  lineinfile:
    path: /etc/csf/csf.conf
    regexp: "^TCP_IN = "
    line: 'TCP_IN = "20,21,22,25,26,53,80,110,143,443,465,587,993,3260,995,2077,2078,2079,2080,2082,2083,2086,2087,2095,2096,8443,2662,31262,5666,54741,52460,9101,9102,9103,49152:65534"'
    create: yes

- name: Restart CSF
  become: yes
  become_user: root
  command: csf -r

- name: Add special permissions to sudoers file
  become: yes
  become_user: root
  blockinfile:
    path: /etc/sudoers
    insertafter: "^# Allow members of group sudo to execute any command"
    block: |
      opsview ALL=NOPASSWD:/usr/sbin/csf
      opsview ALL=NOPASSWD:/usr/sbin/exim
      opsview ALL=NOPASSWD:/usr/sbin/lfd
      opsview ALL=NOPASSWD:/usr/bin/omreport
      opsview ALL=NOPASSWD:/opt/opsview/agent/plugins/check_tcp
      opsview ALL=NOPASSWD:/opt/opsview/agent/plugins/check_disk
    create: yes

- name: Copy the NRPE configuration file
  become: yes
  become_user: root
  copy:
    src: ../../../nrpe.cfg
    dest: /opt/opsview/agent/etc/nrpe.cfg

- name: Copy the check_bandwidth_quota file
  become: yes
  become_user: root
  copy:
    src: ../../../plugins/check_bandwidth_quota.sh
    dest: /opt/opsview/agent/plugins
    group: opsview
    mode: "0750"

- name: Copy the check_csf file
  become: yes
  become_user: root
  copy:
    src: ../../../plugins/check_csf
    dest: /opt/opsview/agent/plugins
    group: opsview
    mode: "0750"

- name: Copy the check_eximmailqueue file
  become: yes
  become_user: root
  copy:
    src: ../../../plugins/check_eximmailqueue
    dest: /opt/opsview/agent/plugins
    group: opsview
    mode: "0750"

- name: Copy the check_dhcp file
  become: yes
  become_user: root
  copy:
    src: ../../../plugins/check_dhcp
    dest: /opt/opsview/agent/plugins
    group: opsview
    mode: "0750"

- name: Copy the check_raid file
  become: yes
  become_user: root
  copy:
    src: ../../../plugins/check_raid.pl
    dest: /opt/opsview/agent/plugins
    group: opsview
    mode: "0750"

- name: Ensure the vnstat service is restarted
  become: yes
  become_user: root
  systemd:
    name: vnstat
    state: restarted

- name: Ensure the opsview service is restarted
  become: yes
  become_user: root
  systemd:
    name: opsview-agent
    state: restarted
