---
- name: Check if cpanel service is installed
  command: "systemctl is-active cpanel"
  ignore_errors: true
  register: cpanel_status

- name: Check if 'CSF' service is installed
  command: "systemctl is-active csf"
  ignore_errors: true
  register: csf_status

- name: Download CSF archive
  get_url:
    url: "https://download.configserver.com/csf.tgz"
    dest: "/tmp/csf.tgz"
  when: cpanel_status.rc == 0 and csf_status.rc != 0

- name: Untar CSF archive
  ansible.builtin.unarchive:
    src: "/tmp/csf.tgz"
    dest: "/tmp/"
    remote_src: yes
  when: cpanel_status.rc == 0 and csf_status.rc != 0

- name: Change to CSF directory and install CSF
  become: yes
  become_user: root
  command:
    cmd: "bash install.sh"
    chdir: "/tmp/csf"
  when: cpanel_status.rc == 0 and csf_status.rc != 0

- name: Install 'Opsview' dependencies
  become: yes
  become_user: root
  package:
    name:
      - wget
      - rpcbind
      - perl
      - bind-utils
      - ksh
      - vnstat
    state: present

- name: Check If 'Opsview' already downloaded or not
  become: yes
  become_user: root
  stat:
    path: /root/opsview-agent-6.8.0.202212070943-1.el8.x86_64.rpm
  register: file_exist

- name: Download the package if it is not exist
  become: yes
  become_user: root
  get_url:
    url: https://opsview-repository.s3-eu-west-1.amazonaws.com/opsview-agents/centos8/opsview-agent-6.8.0.202212070943-1.el8.x86_64.rpm
    dest: /root/opsview-agent-6.8.0.202212070943-1.el8.x86_64.rpm
  when: not file_exist.stat.exists

- name: Ensure the 'Opsview-User' is created
  become: yes
  become_user: root
  user:
    name: opsview
    state: present

- name: Install 'Opsview' RPM package
  become: yes
  become_user: root
  command: rpm -i /root/opsview-agent-6.8.0.202212070943-1.el8.x86_64.rpm
  args:
    creates: /opt/opsview/agent

- name: Start 'Opsview' Agent
  become: yes
  become_user: root
  service:
    name: opsview-agent
    state: started
    enabled: yes

- name: Add special permissions to 'Sudoers' file
  become: yes
  become_user: root
  blockinfile:
    path: /etc/sudoers
    insertafter: "^## Allows members of the users group to shutdown this system"
    block: |
      opsview ALL=NOPASSWD:/usr/sbin/csf
      opsview ALL=NOPASSWD:/usr/sbin/exim
      opsview ALL=NOPASSWD:/usr/sbin/lfd
      opsview ALL=NOPASSWD:/usr/bin/omreport
      opsview ALL=NOPASSWD:/opt/opsview/agent/plugins/check_tcp
      opsview ALL=NOPASSWD:/opt/opsview/agent/plugins/check_disk
    create: yes

- name: Copy the 'NRPE' configuration file
  become: yes
  become_user: root
  copy:
    src: ../../../nrpe.cfg
    dest: /opt/opsview/agent/etc/nrpe.cfg

- name: Copy the 'check_bandwidth_quota' file
  become: yes
  become_user: root
  copy:
    src: ../../../plugins/check_bandwidth_quota.sh
    dest: /opt/opsview/agent/plugins
    group: opsview
    mode: "0750"

- name: Copy the 'check_csf' file
  become: yes
  become_user: root
  copy:
    src: ../../../plugins/check_csf
    dest: /opt/opsview/agent/plugins
    group: opsview
    mode: "0750"

- name: Copy the 'check_eximmailqueue' file
  become: yes
  become_user: root
  copy:
    src: ../../../plugins/check_eximmailqueue
    dest: /opt/opsview/agent/plugins
    group: opsview
    mode: "0750"

- name: Ensure the 'Vnstat' service is restarted
  become: yes
  become_user: root
  systemd:
    name: vnstat
    state: restarted

- name: Ensure the 'Opsview' service is restarted
  become: yes
  become_user: root
  systemd:
    name: opsview-agent
    state: restarted
