---
- name: Install OpsView dependencies
  yum:
    name:
      - rpcbind
      - perl
      - bind-utils
      - ksh
      - epel-release
      - vnstat
    state: present

- name: Check If OpsView already downloaded or not
  stat:
    path: /root/opsview-agent-6.8.0.202212070943-1.el8.x86_64.rpm
  register: file_exist

- name: Download the package if it is not exist
  get_url:
    url: https://opsview-repository.s3-eu-west-1.amazonaws.com/opsview-agents/centos8/opsview-agent-6.8.0.202212070943-1.el8.x86_64.rpm
    dest: /root/opsview-agent-6.8.0.202212070943-1.el8.x86_64.rpm
  when: not file_exist.stat.exists

- name: Ensure the OpsView-user is created
  user:
    name: opsview
    state: present

- name: Install OpsView RPM package
  command: rpm -i /root/opsview-agent-6.8.0.202212070943-1.el8.x86_64.rpm
  args:
    creates: /opt/opsview/agent

- name: Start OpsView Agent
  service:
    name: opsview-agent
    state: started
    enabled: yes

- name: Add OpsView ip address in csf.allow file
  command: csf -a 94.75.230.111

- name: Add allowed ports in csf.conf file
  lineinfile:
    path: /etc/csf/csf.conf
    regexp: "^TCP_IN = "
    line: 'TCP_IN = "20,21,22,25,26,53,80,110,143,443,465,587,993,3260,995,2077,2078,2079,2080,2082,2083,2086,2087,2095,2096,8443,31262,5666,54741,52460,49152:65534"'
    create: yes

- name: Add permissions to sudoers file
  blockinfile:
    path: /etc/sudoers
    insertafter: "^## Allows members of the users group to shutdown this system"
    block: |
      opsview ALL=NOPASSWD:/usr/sbin/csf
      opsview ALL=NOPASSWD:/usr/sbin/exim
      opsview ALL=NOPASSWD:/usr/sbin/lfd
      opsview ALL=NOPASSWD:/usr/bin/omreport
    create: yes

- name: Restart CSF
  command: csf -r

- name: Copy the NRPE configuration file
  copy:
    src: ../../../nrpe.cfg
    dest: /opt/opsview/agent/etc/nrpe.cfg

- name: Copy the check_bandwidth_quota file
  copy:
    src: ../../../check_bandwidth_quota.sh
    dest: /opt/opsview/agent/plugins

- name: Copy the check_csf file
  copy:
    src: ../../../check_csf
    dest: /opt/opsview/agent/plugins

- name: Change ownership of files
  file:
    path: "{{ items }}"
    group: opsview
    mode: "0750"
    with_items:
      - /opt/opsview/agent/plugins/check_bandwidth_quota.sh
      - /opt/opsview/agent/plugins/check_csf

- name: Ensure the service is restarted
  systemd:
    name: vnstat
    state: restarted

- name: Ensure the service is restarted
  systemd:
    name: opsview-agent
    state: restarted
