---
- name: Check if cpanel service is installed
  command: "systemctl is-active cpanel"
  ignore_errors: true
  register: cpanel_status

- name: Check if 'CSF' service is installed
  command: "systemctl is-active csf"
  ignore_errors: true
  register: csf_status

- name: Download CSF archive
  get_url:
    url: "https://download.configserver.com/csf.tgz"
    dest: "/tmp/csf.tgz"
  when: cpanel_status.rc == 0 and csf_status.rc == 0

- name: Untar CSF archive
  ansible.builtin.unarchive:
    src: "/tmp/csf.tgz"
    dest: "/tmp/"
    remote_src: yes
  when: cpanel_status.rc == 0 and csf_status.rc == 0

- name: Change to CSF directory and install CSF
  become: yes
  become_user: root
  command:
    cmd: "bash install.sh"
    chdir: "/tmp/csf"
  when: cpanel_status.rc == 0 and csf_status.rc == 0

- name: Install Opsview dependencies
  become: yes
  become_user: root
  apt:
    name:
      - wget
      - vnstat
      - nagios-nrpe-server
    state: present

- name: Start Nagios Agent
  become: yes
  become_user: root
  service:
    name: nagios-nrpe-server
    state: started
    enabled: yes

- name: Add Opsview Ip address in csf.allow file
  become: yes
  become_user: root
  command: csf -a 94.75.230.111 opsview-server
  when: csf_status.rc == 0

- name: Add Bareos Ip address in csf.allow file
  become: yes
  become_user: root
  command: csf -a 212.83.154.138 bareos-backup-service
  when: csf_status.rc == 0

- name: Change 'lfd will not start while this is enabled' in csf.conf file
  become: yes
  become_user: root
  lineinfile:
    path: /etc/csf/csf.conf
    regexp: '^TESTING = "1"'
    line: 'TESTING = "0"'
    create: yes
  when: csf_status.rc == 0

- name: Add allowed ports in csf.conf file
  become: yes
  become_user: root
  lineinfile:
    path: /etc/csf/csf.conf
    regexp: "^TCP_IN = "
    line: 'TCP_IN = "20,21,22,25,26,53,80,110,143,443,465,587,993,3260,995,2077,2078,2079,2080,2082,2083,2086,2087,2095,2096,8443,2662,31262,5666,54741,52460,9101,9102,9103,49152:65534"'
    create: yes
  when: csf_status.rc == 0

- name: Restart CSF
  become: yes
  become_user: root
  command: csf -r
  when: csf_status.rc == 0

- name: Add special permissions to sudoers file
  become: yes
  become_user: root
  blockinfile:
    path: /etc/sudoers
    insertafter: "^# Allow members of group sudo to execute any command"
    block: |
      nagios ALL=NOPASSWD:/usr/sbin/csf
      nagios ALL=NOPASSWD:/usr/sbin/exim
      nagios ALL=NOPASSWD:/usr/sbin/lfd
      nagios ALL=NOPASSWD:/usr/bin/omreport
      nagios ALL=NOPASSWD:/usr/lib/nagios/plugins/check_tcp
      nagios ALL=NOPASSWD:/usr/lib/nagios/plugins/check_disk
    create: yes

- name: Copy the NRPE configuration file
  become: yes
  become_user: root
  copy:
    src: ../../../nrpe.cfg
    dest: /etc/nagios/nrpe.cfg

- name: Copy the check_bandwidth_quota file
  become: yes
  become_user: root
  copy:
    src: ../../../plugins/check_bandwidth_quota.sh
    dest: /usr/lib/nagios/plugins
    group: opsview
    mode: "0750"

- name: Copy the check_csf file
  become: yes
  become_user: root
  copy:
    src: ../../../plugins/check_csf
    dest: /usr/lib/nagios/plugins
    group: opsview
    mode: "0750"

- name: Copy the check_eximmailqueue file
  become: yes
  become_user: root
  copy:
    src: ../../../plugins/check_eximmailqueue
    dest: /usr/lib/nagios/plugins
    group: opsview
    mode: "0750"

- name: Copy the check_dhcp file
  become: yes
  become_user: root
  copy:
    src: ../../../plugins/check_dhcp
    dest: /usr/lib/nagios/plugins
    group: opsview
    mode: "0750"

- name: Copy the check_raid file
  become: yes
  become_user: root
  copy:
    src: ../../../plugins/check_raid.pl
    dest: /usr/lib/nagios/plugins
    group: opsview
    mode: "0750"

- name: Ensure the vnstat service is restarted
  become: yes
  become_user: root
  systemd:
    name: vnstat
    state: restarted

- name: Ensure the opsview service is restarted
  become: yes
  become_user: root
  systemd:
    name: opsview-agent
    state: restarted
